docs(loader): add config env details and demos
artusjs/spec pull request #12
Opened 2022-02-28 12:11 UTC by BeAce

2022-03-01 00:43 UTC, fengmk2 commented on documentation/core/2.loader.md
> +- config 支持异步，可通过异步函数来实现更加复杂的配置
可以补充一下为什么需要支持异步，将复杂的配置场景举例几个。

2022-03-01 02:03 UTC, hyj1991 commented on documentation/core/2.loader.md
> +- config 支持异步，可通过异步函数来实现更加复杂的配置
> 可以补充一下为什么需要支持异步，将复杂的配置场景举例几个。

这个版本默认单进程模型，没有 agent 承载远程配置获取的前置能力了，所以需要将 config 生命周期也修改为异步以便放置类似的异步配置加载逻辑

2022-03-02 07:31 UTC, noahziheng requested changes

2022-03-02 07:31 UTC, noahziheng commented on documentation/core/2.loader.md
> +- 可以通过 setConfig API，在 config 加载完成后对 config 进行修改， 以便框架记录配置改动的操作位置，方便分析
这一点还有待讨论吧，我是一直觉得 config 最好是静态的不要改最好，否则类型分析还是会炸的

2022-03-02 11:02 UTC, noahziheng approved these changes
LGTM

2022-03-04 01:36 UTC, hyj1991 approved these changes

2022-03-04 01:44 UTC, merged